# -*- coding: utf-8 -*-
"""LVADSUSR70-Anjali-FA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o1K76YK_m0le8n2vVBGKGXFEBHUwIh31

**1**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#loading the dataset
df=pd.read_excel("/content/Walmart_Dataset Python_Final_Assessment.xlsx")
#reading the dataset to have an idea
df.head()

#to know how many rows and columns are there
rows=df.shape[0]
columns=df.shape[1]
print("no of rows: ",rows)
print("no of columns: ",columns)

#to know the columns name
df.columns

#to know the columns which have numerical data
numerical_data=[]
data=pd.DataFrame(df.describe())
numerical_data=list(data.columns)
print("Numerical Data: ",numerical_data)

#to know the columns which have categorical data
categorical_data=[]
for cols in df.columns:
  if cols not in numerical_data:
    categorical_data.append(cols)

print("Categorical Data: ",categorical_data)

#to know the datatype of columns and count of null values
df.info()
#no null values are found

#to know the statistical details of numerical values
df.describe()

"""2"""

#to check the null values
df.isnull().sum()

#to check if there are duplicates rows or not
df.duplicated().sum()

"""There are no duplicates and null values found.

3
"""

df.describe()

"""4"""

#mean sales according to the category
category_wise_total_sales= df[["Category","Sales"]].groupby("Category").sum()
plt.figure(figsize=(10,6))
sns.heatmap(category_wise_total_sales,annot=True)
#by this graph we can have a view that category have highest sales or lowest sales

Location_wise_total_sales= df[["Geography","Sales"]].groupby("Geography").sum()
plt.figure(figsize=(10,6))
sns.heatmap(Location_wise_total_sales,cmap='jet')

category_wise_avg_sales= df[["Category","Sales"]].groupby("Category").aggregate({'sum'})
sns.histplot(category_wise_avg_sales,kde=True)
plt.ylabel('Distribution')
plt.title("How sales is Distributed Category wise?")

"""5"""

#correlation between numerical data
df.corr()

plt.scatter(df['Sales'],df['Quantity'])
#this plot shows that quantity is little bit correlated with sales

plt.scatter(df['Sales'],df['Profit'])
#this shows that profit and sales are correlated to much extend

"""6"""

#to identify outliers for numerical data we will use boxplot
plt.subplot(1,3,1)
plt.boxplot(df["Sales"])
plt.xlabel("Sales")
plt.subplot(1,3,2)
plt.boxplot(df["Quantity"])
plt.xlabel("Quantity")
plt.subplot(1,3,3)
plt.boxplot(df["Profit"])
plt.xlabel("Profit")
plt.show()

#remove outliers
df=df[df["Sales"]<8000]
df=df[(df["Profit"]<2000) & (df["Profit"]>-2000)]
#Quantity columns outliers is not removed as it can be used to analysed

df.shape #so we have removed 3 rows which had included outliers

"""7"""

df['Order Date'] = pd.to_datetime(df['Order Date'])
df["Year"]=(df['Order Date'].dt.year)
df1=df[["Year","Sales","Profit"]].groupby("Year").sum().plot()

#year wise sales for each category
category=list(df["Category"].value_counts().index)
for i in category:
  df1=df[["Sales","Year"]].groupby(["Year"]).sum().plot()

df1=df[["EmailID","Order ID"]].groupby("EmailID").count().reset_index()
df2=df[["EmailID","Sales"]].groupby("EmailID").sum().reset_index()
final=pd.merge(df1,df2)
final=final.sort_values(by=["Sales","Order ID"],ascending=False)
Top_5=final.head(5).reset_index(drop=True)
Top_5

df['Order Date'] = pd.to_datetime(df['Order Date'])

df['Order Date'] = df.groupby('EmailID')['Order Date'].diff().dt.total_seconds()

average_time_between_orders = df.groupby('EmailID')['Order Date'].mean()

print("Average time between orders for each customer:")
print(round(average_time_between_orders,2))
#average_time_between_orders.plot()

"""8

1. As we have seen that most sales occur in Location scottsdale,San Clemente
California, we can have more percentage of order fulfilment on such locations.
And can increase the supply chain of bookcases and phones as well as these are the categories which contributed to the most sales.

2. The availability of the product at that location, contribute to the sales there. These are the location with highest number of sales scottsdale,San Clemente, so the availability of products and order fulfilment as early as possible there will help.

3. These are the top 5 customers which have purchased high value products
EdwardHooks@gmail.com
	JaneWaco@gmail.com
  KarenFerguson@gmail.com
  NickCrebassa@gmail.com
  ClayLudtke@gmail.com
  we can have a check on there geography location and can have our products there.
  High value customers depends on the geography location.
  And there we can see a pattern with the quantity they ordered and sales they produced, as quantity is correlated with the sales they generate.
  
   
"""